# Generated by Django 4.1.2 on 2022-10-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('cn_number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=50)),
                ('destination_city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('default_origin_city', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('pieces', models.IntegerField()),
                ('customer_reference_number', models.CharField(max_length=50)),
                ('service_type', models.CharField(max_length=50)),
                ('flyer_number', models.CharField(max_length=50)),
                ('special_handling', models.CharField(max_length=50)),
                ('product_detail', models.CharField(max_length=100)),
                ('cash_amount', models.IntegerField(max_length=50)),
                ('pickup_city', models.CharField(max_length=50)),
            ],
        ),
    ]
