# Generated by Django 4.1.2 on 2022-10-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('username', models.CharField(max_length=50)),
                ('customer_id', models.IntegerField(default=523544, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='username',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cash_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_reference_number',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='default_origin_city',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='destination_city',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='flyer_number',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='mobile_number',
            field=models.CharField(default=' ', max_length=11),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_city',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pieces',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='product_detail',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='special_handling',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
