# Generated by Django 4.1.2 on 2022-10-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0003_bookinglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinglog',
            name='dateTime',
            field=models.CharField(default='21/10/2022 11:57:13', max_length=100),
        ),
    ]
