# Generated by Django 4.1.2 on 2022-10-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0004_bookinglog_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinglog',
            name='record_no',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
