# Generated by Django 4.1.2 on 2022-10-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0006_alter_booking_cn_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_no', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('username', models.CharField(default=' ', max_length=50)),
                ('vendor_name', models.CharField(default=' ', max_length=100)),
                ('product_name', models.CharField(default=' ', max_length=50)),
                ('product_description', models.CharField(default=' ', max_length=200)),
                ('sku', models.IntegerField(default=0)),
                ('quantity_given', models.IntegerField(default=0)),
                ('quantity_in_process', models.IntegerField(default=0)),
                ('quantity_sold', models.IntegerField(default=0)),
                ('quantity_available', models.IntegerField(default=0)),
                ('product_image', models.FileField(null=True, upload_to='images/', verbose_name='')),
            ],
        ),
        migrations.AlterField(
            model_name='bookinglog',
            name='dateTime',
            field=models.CharField(default='2022-10-21 11:57:13', max_length=100),
        ),
    ]
