# Generated by Django 4.1.2 on 2022-10-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0009_alter_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='username',
        ),
        migrations.AddField(
            model_name='product',
            name='cn_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
