# Generated by Django 4.1.2 on 2022-10-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0010_remove_product_username_product_cn_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_no',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
