# Generated by Django 4.1.2 on 2022-10-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0012_alter_product_product_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cn_number',
        ),
        migrations.AddField(
            model_name='product',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
