# Generated by Django 4.1.2 on 2022-10-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0013_remove_product_cn_number_product_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinglog',
            name='pieces',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='bookinglog',
            name='status',
            field=models.CharField(default='Booked', max_length=50),
        ),
    ]
